# dependabot.yaml reference: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
#
# Notes:
# - Status and logs from dependabot are provided at
#   https://github.com/jupyterhub/action-k8s-await-workloads/network/updates.
# - YAML anchors are not supported here or in GitHub Workflows.
# - We explicitly set the "maintenance" label to help our changelog generator
#   tool github-activity to categorize PRs.
#
version: 2
updates:
  # Update `package.json` and `package-lock.json`
  - package-ecosystem: npm
    directory: /
    versioning-strategy: increase-if-necessary
    allow:
      - dependency-type: production
    schedule:
      interval: weekly
      time: "05:00"
      timezone: Etc/UTC
    labels:
      - maintenance
      - dependencies

  # Maintain dependencies in our GitHub Workflows
  - package-ecosystem: github-actions
    directory: /
    labels: [ci]
    schedule:
      interval: monthly
      time: "05:00"
      timezone: Etc/UTC
