# Reference: https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/metadata-syntax-for-github-actions
---
name: Await workloads
description: >
  Awaits Ready / Completed status of Kubernetes workloads, namely Deployments,
  StatefulSets, DaemonSets, and Jobs. If a workload's pods have a container that
  restarts, the wait will stop.

branding:
  icon: server
  color: purple

inputs:
  # Manually keep the descriptions synced with the readme!
  max-restarts:
    default: 0
    description: Maximum restarts of a container to tolerate before aborting wait.
    required: false
  max-time:
    default: 0
    description: Maximum total time to await all workloads.
    required: false

outputs:
  # Manually keep the descriptions synced with the readme!
  # FIXME: measure total duration waited
  duration:
    description: The total duration waited.
    value: "not yet implemented"

runs:
  using: "composite"
  steps:
    - name: Validate input
      shell: bash
      # FIXME: Add validation logic
      run: |
        exit 0

    - name: Await workloads
      shell: bash
      env:
        INPUT_MAX_RESTARTS: "${{ inputs.max-restarts }}"
        INPUT_MAX_TIME: "${{ inputs.max-time }}"
      run: |
        ${{ github.action_path }}/k8s-await-workloads
