# Reference: https://help.github.com/en/articles/metadata-syntax-for-github-actions
---
name: Await Kubernetes workloads
# Manually keep the description synced with the readme!
description: >
  An action to help you await successful startup of Kubernetes workloads:
  DaemonSets, Deployments, and StatefulSets.

branding:
  icon: server
  color: purple

inputs:
  # Manually keep the descriptions synced with the readme!
  workloads:
    default: ""
    required: false
    description: >
      Await a subset of the namespace's workloads. Example:
      "deployment/hub,statefulset/user-placeholder".
  namespace:
    default: ""
    required: false
    description: >
      Await workloads within this namespace instead of the current contexts
      namespace.
  timeout:
    default: "0"
    required: false
    description: >
      Aborts after this time in seconds. Defaults to `-1` which means infinite.
  max-restarts:
    default: "0"
    required: false
    description: >
      Aborts after this many container restarts for any given container.
      Defaults to `-1` which means infinite.

runs:
  using: "node12"
  main: "dist/index.js"
