---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: healthy
  template:
    metadata:
      labels:
        app: healthy
    spec:
      containers:
        - name: busybox
          image: busybox
          command:
            - sh
            - -c
            - >
              printf "This pod is ready\nfor its\neternal sleep!\n";
              sleep infinity;
