---
apiVersion: v1
kind: Pod
metadata:
  name: test-healthy-1
spec:
  containers:
    - name: busybox
      image: busybox
      command:
        - sh
        - -c
        - >
            printf "This pod is ready\nfor its\neternal sleep!\n";
            sleep infinity;
---
apiVersion: v1
kind: Pod
metadata:
  name: test-healthy-2
spec:
  containers:
    - name: busybox
      image: busybox
      command:
        - sh
        - -c
        - >
            printf "This pod is ready\nfor its\neternal sleep!\n";
            sleep infinity;
