---
apiVersion: v1
kind: Pod
metadata:
  name: test-non-ready
spec:
  containers:
    - name: busybox
      image: busybox
      # readinessProbe to ensure this pod never becomes ready
      readinessProbe:
        initialDelaySeconds: 0
        httpGet:
          path: /
          port: 1234
      command:
        - sh
        - -c
        - >
          printf "This pod is ready\nfor its\neternal sleep!\n";
          sleep infinity;
