---
apiVersion: v1
kind: Pod
metadata:
  name: test-pending
spec:
  # nodeSelector to ensure this pod never becomes scheduled
  nodeSelector:
    test.jupyter.org/node: no-node-has-this-label
  containers:
    - name: busybox
      image: busybox
