---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: restarted
spec:
  replicas: 2
  selector:
    matchLabels:
      app: restarted
  template:
    metadata:
      labels:
        app: restarted
    spec:
      # We write a file to an empty-dir volume to remember if the container has
      # started or not before, and ensure to crash on first startup.
      volumes:
        - name: empty-dir
          emptyDir: {}
      containers:
        - name: busybox
          image: busybox
          volumeMounts:
            - mountPath: /tmp/mount
              name: empty-dir
          command:
            - sh
            - -c
            - >
              if [ -f "/tmp/mount/here" ]; then
                  printf "This is logged \nafter the container has restarted \nand is about to sleep...\n";
                  sleep infinity;
              else
                  touch /tmp/mount/here;
                  printf "This is logged \njust before the container \nis about to crash!\n";
                  exit 123;
              fi;
          # readinessProbe helps us avoid becoming ready until an initial
          # restart has been made.
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - cat /tmp/mount/here
            initialDelaySeconds: 0
            periodSeconds: 2
